language: python
python:
  - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - python setup.py install
# command to run tests
script:
    - python tests/merge_sort_tests.py
    - python tests/quick_sort_tests.py
    - python tests/radix_sort_tests.py
